---
title: "canu"
author: "Roberto Canu"
format:
  html:
    code-fold: false
    message: false
    warning: false
editor: visual
---

```{r}
here::i_am("grades.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
library(readr)
library(lubridate)
```

# INTRODUCTION

## Study organisation

### Question 1

```{r}
courses <- vroom(here("datafold", "courses.csv"))
```
## Question 2 

```{r}
courses |>
  arrange(course) |>
  knitr::kable()
```

## 1.2 Students 

### Question 3

```{r}
students <- read_delim(
  here("datafold", "students.csv"),
  col_types = cols(
    birth_date = col_date(),
    group = col_factor(),
    id = col_integer()
  )
)
```

The `birth_date` column of the `students` data frame is of class *`r class(students$birth_date)`*.

## 1.3 Grades 

### Question 4 
```{r}
grades <- read_delim(
  here("datafold", "grades.csv"),
  delim = ":",
  na = "_"
)
```
# Student Population analysis

### Question 5

```{r}
students |>
  summarise(n = n(), .by = group) |>
  ggplot(aes(x = as.integer(as.character(group)), y = n)) +
  geom_col() +
  labs(x = "Group", y = "Count")
```

### Question 6 
```{r}
students |>
  summarise(n = n(), .by = c(group, sex)) |>
  ggplot(aes(x = as.integer(as.character(group)), y = n, fill = sex)) +
  geom_col(position="fill") +
  labs(x = "Group", y = "Gender Balance")

```


### Question 7 
```{r}
students <- students |>
  mutate(age = time_length(today() - birth_date, unit = "year")) 

students |>
  ggplot(aes(x = age)) +
  geom_density(bw = "sj") +
  geom_rug(alpha = 0.1) +
  labs(x = "Age", y = "Density")
```

### Question 8 
```{r}
students |>
  summarise(median_age = round(median(age)), .by = group) |>
  arrange(as.integer(as.character(group))) |> 
  knitr::kable()
```

### Question 9 
```{r}
students |>
  slice_max(age, by = group) |>
  select(id, sex, age, group) |>
  arrange(desc(age)) |>
  knitr::kable()
```



